
- hosts: servers
  roles:
    - { role: datadog.datadog, become: yes }
  vars_files:
    - variables.yml
  vars:
    datadog_site: "datadoghq.com"
    datadog_agent_version: "7.32.0"
    datadog_config:
      apm_config:
        enabled: true
      process_config:
        enabled: "true"
    system_probe_config:
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
    network_config:
      enabled: true
