
- hosts: web_servers
  roles:
    - { role: datadog.datadog, become: yes }
  vars_files:
    - variables.yml
  vars:
    datadog_site: "datadoghq.com"
    datadog_agent_version: "7.32.0"
    datadog_checks:
      apache:
        init_config:
        instances:
          - apache_status_url: http://localhost/server-status?auto
